#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap.php';

use KlimovPaul\PhpProjectUpdate\Console\ProjectUpdateCommand;
use Symfony\Component\Console\Application;

$app = new Application();

$app->add(new ProjectUpdateCommand($config));

$app->run();
